In [1]:
# Standard scientific Python imports
import matplotlib.pyplot as plt
from sklearn import svm, metrics

In [2]:
import os
import numpy as np
from pandas.io.parsers import read_csv
from sklearn.utils import shuffle
from lasagne.layers import InputLayer, DenseLayer, batch_norm
import cPickle as pickle

C:\Users\Nishant\AppData\Roaming\Python\Python27\site-packages\theano\tensor\signal\downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


In [3]:
TrainingSet = '.\\data\\fer2013.csv'
#loading the data and splitting into training and test set
df = read_csv(os.path.expanduser(TrainingSet))
df['pixels'] = df['pixels'].apply(lambda im: np.fromstring(im, sep=' '))
output_label = np.array(df['emotion'].values)
features_image = np.vstack(df['pixels'].values)  # scale pixel values to [0, 1]
features_image = features_image.astype(np.float32)
x_train = features_image[:30000]
y_train = output_label[:30000]
x_test = features_image[30000:]
y_test = output_label[30000:]
y_train = y_train.astype(np.uint8)
y_test = y_test.astype(np.uint8)

In [9]:
# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001, verbose = True)
classifier.fit(x_train, y_train)

[LibSVM]

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=True)

In [ ]:
# Saving the model for future use
import cPickle as pickle
with open('.\\TrainedModels\\SVM.pickle', 'wb') as f:
    pickle.dump(classifier, f, -1)

In [8]:
# loading preTrained Model
f = open('.\\TrainedModels\\SVM.pickle', 'rb')
classifier = pickle.load(f)
f.close()

In [9]:
# use the classifier to predict the test data
predicted = classifier.predict(x_test)

In [17]:
#print classifier.score(x_train, y_train)
from __future__ import division
y_diff = y_test - predicted
len(y_diff[y_diff != 0])
print 'Accuracy of the model: ' + str((len(y_diff) - len(y_diff[y_diff != 0]))/ len(y_diff))

Accuracy of the model: 0.320536775947


In [12]:
# visualize the performance of the classifier
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(y_test, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, predicted))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=True):
             precision    recall  f1-score   support

          0       0.96      0.07      0.13       780
          1       1.00      0.29      0.45        90
          2       0.88      0.09      0.16       828
          3       0.27      1.00      0.42      1468
          4       0.91      0.03      0.06      1028
          5       0.98      0.29      0.45       673
          6       0.97      0.04      0.07      1020

avg / total       0.77      0.32      0.23      5887


Confusion matrix:
[[  55    0    3  721    1    0    0]
 [   0   26    0   64    0    0    0]
 [   1    0   75  749    1    1    1]
 [   0    0    0 1466    0    2    0]
 [   1    0    3  994   30    0    0]
 [   0    0    4  472    0  197    0]
 [   0    0  